services:
  nginx:
    image: nginx:latest
    container_name: gostop-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - client
      - server
    networks:
      - gostop-net

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: gostop-client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - gostop-net
    environment:
      - WDS_SOCKET_HOST=client
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gostop-server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - db
    networks:
      - gostop-net

  db:
    image: mongo:latest
    container_name: gostop-db
    volumes:
      - ./mongo-data:/data/db
    restart: always
    networks:
      - gostop-net

networks:
  gostop-net:
    driver: bridge