FROM node:20-alpine
WORKDIR /usr/src/app
COPY server/package*.json ./
RUN npm install
COPY server/ .
# NestJS는 실행 시 3001 포트를 사용하도록 설정할 예정
EXPOSE 3001
# 이 부분은 실제 NestJS 프로젝트 구조에 따라 달라질 수 있음
# CMD ["npm", "run", "start:dev"] 
# 임시로 서버를 계속 실행 상태로 두기 위한 커맨드
CMD ["npm", "run", "start:dev"]