services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: gostop-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - gostop-net

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gostop-server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - db
    networks:
      - gostop-net

  db:
    image: mongo:latest
    container_name: gostop-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: always
    networks:
      - gostop-net

networks:
  gostop-net:
    driver: bridge